<?php
//1.4

/*
  _____                 _                           _     _
 |_   _|               | |                         | |   (_)
   | |    _ __    ___  | |_   _ __   _   _    ___  | |_   _    ___    _ __    ___
   | |   | '_ \  / __| | __| | '__| | | | |  / __| | __| | |  / _ \  | '_ \  / __|
  _| |_  | | | | \__ \ | |_  | |    | |_| | | (__  | |_  | | | (_) | | | | | \__ \
 |_____| |_| |_| |___/  \__| |_|     \__,_|  \___|  \__| |_|  \___/  |_| |_| |___/

This file is automatically generated with default values if it does not exist.
Just delete the file to start from scratch!
You will not lose your settings on update!

The $mobile_width value is the maximum width in pixels to consider a mobile device.
If you want to enable gradient, set the gradient value to true, otherwise false.
If gradient is set to false the color value is what you need to set.
*/

// Display on mobile (true = yes, false = no)? false by default.
$enable_on_mobile = 'false';

// Maximum width of screen to consider a mobile device. 600px by default.
$mobile_width = '600px';

// Do you want to enable the loading bar on the login page (true = yes, false = no)? true by default.
$enable_on_login = 'true';

// Do you want gradient (true = yes, false = no)? false by default.
$gradient = 'false';

// Start gradient color (ex. red or #ff0000). #ff0000 by default.
$start_gradient = '#ff0000';

// End gradient color (ex. green or #008000) #008000 by default.
$end_gradient = '#008000';

// Set color of the loading bar if gradient is false (ex. darkred or #8b0000). #d63031 by default.
$color = '#d63031';

// Set height of the loading bar (ex. 5px or 10px). 5px by default.
$height = '5px';

// Set the position of the loading bar (top = top, bottom = bottom). top by default.
$position = 'top';

?>